### PR TITLE
Update Czech l10n

### PR DESCRIPTION
**Pull request by MikkCZ**
Some of the messages sounded unnatural, or used uncommon terminology.

### CODE REVIEW

**Comment by MikkCZ** [comment]
Also I would like to ask whether to find the messages used for the challenges. Some of them are pretty inaccurate in Czech, e.g. asking to select _motorová [sběrnice](https://cs.wikipedia.org/wiki/Sb%C4%9Brnice)_, while it should be _[autobus](https://cs.wikipedia.org/wiki/Autobus)_. I expect it says _motor bus_ in original. And there are more that sound like machine translation.

**Comment by MikkCZ** [comment]
@wontem @DSergiu @e271828- may I ask you for review?

**Comment by DSergiu** [comment]
@MikkCZ Thank you for the translation improvements. We will review it soon. 
Would you mind merging master and solving the conflict?

**Comment by MikkCZ** [comment]
Thank you. I updated the PR now.

**Review by DSergiu — APPROVED** [review]

**Comment by MikkCZ** [comment]
> Also I would like to ask whether to find the messages used for the challenges. Some of them are pretty inaccurate in Czech, e.g. asking to select _motorová [sběrnice](https://cs.wikipedia.org/wiki/Sb%C4%9Brnice)_, while it should be _[autobus](https://cs.wikipedia.org/wiki/Autobus)_. I expect it says _motor bus_ in original. And there are more that sound like machine translation.

Can we do something about the challenge text, at least the one with _motor bus_?

**Comment by MikkCZ** [comment]
@DSergiu @e271828- where can I update translation of the challenges, as mentioned above, please?

**Pull request merged**
