### PR TITLE
Serbian Cyrillic (sr.json) fixes and improvements

### PR DESCRIPTION
**Pull request by freschstudio**
Serbian language is digraphic and it supports both alphabets. Added Serbian Latin and improved Serbian Cyrillic.

### CODE REVIEW

**Comment by e271828-** [comment]
@freschstudio thanks! Can you split this into two PRs? The sr improvements can be merged now, but adding sr-LT requires some additional work.

**Comment by freschstudio** [comment]
> @freschstudio thanks! Can you split this into two PRs? The sr improvements can be merged now, but adding sr-LT requires some additional work.

I've removed Serbian Latin from this PR and retained the previous corrections to Serbian Cyrillic.

**Comment by freschstudio** [comment]
Any updates regarding this?

**Review by e271828- — APPROVED** [review]

**Comment by e271828-** [comment]
@freschstudio apologies, missed your update. Please resolve conflicts and we'll get it merged + shipped pretty shortly.

**Pull request merged**
